// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWD09QLvFsy5Se6acmwrcxkW_ZhJXCfdc',
    appId: '1:999775655239:web:00c6d2491ac28a08a62862',
    messagingSenderId: '999775655239',
    projectId: 'hoabactravel-3650d',
    authDomain: 'hoabactravel-3650d.firebaseapp.com',
    storageBucket: 'hoabactravel-3650d.appspot.com',
    measurementId: 'G-PZ1BPXWLTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGGfFAcJKkHD_A5CidpX6gltggLkKD6KY',
    appId: '1:999775655239:android:25ede9d2d60ced95a62862',
    messagingSenderId: '999775655239',
    projectId: 'hoabactravel-3650d',
    storageBucket: 'hoabactravel-3650d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKAwpUdU8qfWk-hwXjDaFov2EyU2vC1EA',
    appId: '1:999775655239:ios:081eb1b33c813211a62862',
    messagingSenderId: '999775655239',
    projectId: 'hoabactravel-3650d',
    storageBucket: 'hoabactravel-3650d.appspot.com',
    androidClientId: '999775655239-m2uha4j95670n32mr1f3p39ca19663dc.apps.googleusercontent.com',
    iosClientId: '999775655239-h4cn38tr6bvej5r21gcdgcafgoaki5s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoabactravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKAwpUdU8qfWk-hwXjDaFov2EyU2vC1EA',
    appId: '1:999775655239:ios:8812938eaa111d5ea62862',
    messagingSenderId: '999775655239',
    projectId: 'hoabactravel-3650d',
    storageBucket: 'hoabactravel-3650d.appspot.com',
    androidClientId: '999775655239-m2uha4j95670n32mr1f3p39ca19663dc.apps.googleusercontent.com',
    iosClientId: '999775655239-cj8vl1pu7mhc842v2qpva9nef2v31rqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoabactravel.RunnerTests',
  );
}
